# Generated by Django 2.1.5 on 2019-02-07 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Draft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[(1, 'ios'), (2, 'android')], default=1, max_length=1, verbose_name='裝置平台')),
                ('version', models.CharField(max_length=10, verbose_name='版本號')),
                ('update_text', models.TextField(max_length=200, verbose_name='訊息文字')),
                ('force_update', models.BooleanField(default=False, verbose_name='是否強更')),
                ('pub_date', models.DateTimeField(verbose_name='發布日期')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='建立日期')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
            ],
            options={
                'verbose_name': '更新文字草稿',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_review', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='建立日期')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
            ],
        ),
        migrations.CreateModel(
            name='UpdateInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=20)),
                ('version', models.CharField(max_length=10)),
                ('update_text', models.TextField(max_length=200)),
                ('force_update', models.BooleanField(default=False)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('is_pub', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='建立日期')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='draft',
            unique_together={('platform', 'version')},
        ),
    ]
