# Generated by Django 2.1.5 on 2019-02-07 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('versionInfo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='draft',
            field=models.ForeignKey(default=1234, on_delete=django.db.models.deletion.CASCADE, to='versionInfo.Draft'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='is_review',
            field=models.BooleanField(default=False, verbose_name='是否通過'),
        ),
    ]
