# Generated by Django 2.1.5 on 2019-02-09 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('versionInfo', '0003_auto_20190209_1116'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': '審核'},
        ),
        migrations.AddField(
            model_name='draft',
            name='is_review',
            field=models.BooleanField(default=False, verbose_name='送審'),
        ),
        migrations.AlterField(
            model_name='draft',
            name='platform',
            field=models.CharField(choices=[('1', 'ios'), ('2', 'android')], default='1', max_length=10, verbose_name='裝置平台'),
        ),
        migrations.AlterField(
            model_name='review',
            name='draft',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='versionInfo.Draft', verbose_name='草稿'),
        ),
    ]
