# Generated by Django 2.1.5 on 2019-02-09 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('versionInfo', '0004_auto_20190209_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='is_review',
        ),
        migrations.AddField(
            model_name='review',
            name='status',
            field=models.CharField(choices=[('0', 'WAITING'), ('1', 'PASS'), ('2', 'NOT_PASS')], default='0', max_length=2, verbose_name='審核狀態'),
        ),
        migrations.AlterField(
            model_name='draft',
            name='is_review',
            field=models.BooleanField(default=False, verbose_name='完成送審'),
        ),
        migrations.AlterField(
            model_name='draft',
            name='platform',
            field=models.CharField(choices=[('ios', 'ios'), ('android', 'android')], default='ios', max_length=10, verbose_name='裝置平台'),
        ),
    ]
