# Generated by Django 2.1.5 on 2019-02-07 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('versionInfo', '0004_auto_20190207_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draft',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='建立日期'),
        ),
        migrations.AlterField(
            model_name='draft',
            name='force_update',
            field=models.BooleanField(default=False, verbose_name='是否強更'),
        ),
        migrations.AlterField(
            model_name='draft',
            name='platform',
            field=models.CharField(choices=[('IOS', 'ios'), ('ANDROID', 'android')], default='IOS', max_length=20, verbose_name='裝置平台'),
        ),
        migrations.AlterField(
            model_name='draft',
            name='update_date',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日期'),
        ),
        migrations.AlterField(
            model_name='draft',
            name='update_text',
            field=models.TextField(max_length=200, verbose_name='訊息文字'),
        ),
        migrations.AlterField(
            model_name='draft',
            name='version',
            field=models.CharField(max_length=10, verbose_name='版本號'),
        ),
        migrations.AlterField(
            model_name='updateinfo',
            name='update_text',
            field=models.TextField(max_length=200),
        ),
    ]
