# Generated by Django 2.1.5 on 2019-02-11 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('versionInfo', '0005_auto_20190209_1434'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': '草稿審核'},
        ),
        migrations.AlterModelOptions(
            name='updateinfo',
            options={'verbose_name': '版本發佈訊息'},
        ),
        migrations.AlterField(
            model_name='draft',
            name='is_review',
            field=models.BooleanField(default=False, verbose_name='提交送審'),
        ),
    ]
