# Generated by Django 2.1.5 on 2019-02-07 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('versionInfo', '0005_auto_20190207_1429'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='draft',
            options={'verbose_name': '版本更新草稿'},
        ),
        migrations.AlterField(
            model_name='draft',
            name='pub_date',
            field=models.DateTimeField(verbose_name='發布日期'),
        ),
        migrations.AlterUniqueTogether(
            name='draft',
            unique_together={('platform', 'version')},
        ),
    ]
