# Generated by Django 2.1.5 on 2019-02-11 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('versionInfo', '0006_auto_20190211_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='draft',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='versionInfo.Draft', verbose_name='草稿'),
        ),
    ]
