# Generated by Django 2.1.5 on 2019-02-11 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('versionInfo', '0007_auto_20190211_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='update_info',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='versionInfo.UpdateInfo', verbose_name='發佈更新'),
        ),
    ]
