# Generated by Django 2.1.5 on 2019-02-11 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('versionInfo', '0008_review_update_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='updateinfo',
            name='is_pub',
        ),
    ]
