# Generated by Django 2.1.5 on 2019-02-11 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('versionInfo', '0009_remove_updateinfo_is_pub'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='updateinfo',
            name='force_update',
        ),
        migrations.RemoveField(
            model_name='updateinfo',
            name='platform',
        ),
        migrations.RemoveField(
            model_name='updateinfo',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='updateinfo',
            name='update_text',
        ),
        migrations.RemoveField(
            model_name='updateinfo',
            name='version',
        ),
        migrations.AddField(
            model_name='updateinfo',
            name='info',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='versionInfo.Draft', verbose_name='發布訊息'),
        ),
    ]
