# Generated by Django 2.1.5 on 2019-02-11 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('versionInfo', '0011_auto_20190211_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='update_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='versionInfo.UpdateInfo', verbose_name='發佈更新'),
        ),
    ]
